### ISSUE TITLE
Improvements to layout of job form view

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-ui#46]
- [x] As is the case in the [finished job view](https://github.com/daisy/pipeline-ui/issues/42), the division into "Required information" and "Options" boxes doesn't work very well when the window gets a bit smaller (see also [#10](https://github.com/daisy/pipeline-ui/issues/10)). On top of that, it just isn't so logical that a part of the optional information is already presented (visually) while there isn't enough space to present all required information.
- [ ] The form could be split up into two steps: first the user is presented only the "required information", in a next step only the "options".
- [x] The option description text is wrapped early, it is not adapted to the width of the containing ("Required information" or "Options") box. Perhaps a maximum width makes sense, but the current maximum width seems a bit small.
- [x] By default it is enough that only the short option descriptions are shown. By presenting the most important information first the user quickly gets an overview of the available options. The user can then request the long descriptions if needed. Marisa expressed her concern about the noise that a lot of show/hide buttons would cause, but IMO this is only a small sacrifice, and there might be ways to make it less noisy.

**Comment by marisademeglio** [comment]
3 of these 4 things are fixed by https://github.com/daisy/pipeline-ui/commit/1ee35b8fa5497cf617665b50611e16dd6a80cc48

Do you want to make a separate issue for the second item in the list above?

**Comment by bertfrees** [comment]
Hmm no let's just drop that second item. It was a suggestion, but if there are no concrete plans to do it I would leave it. We don't want to end up with a whole backlog of ideas that we'll never implement.

**Comment by marisademeglio** [comment]
Agree. We know that future iterations could include drag and drop (#27) and a wizard-like interface (e.g. your second item above), but that's a bigger change than the other items in the list as it impacts the UX flow and not just the placement of information on screen.

**Comment by bertfrees** [comment]
> The option description text is wrapped early, it is not adapted to the width of the containing ("Required information" or "Options") box. Perhaps a maximum width makes sense, but the current maximum width seems a bit small.

The option description test is still not adapted to the width of the container.

**Comment by marisademeglio** [comment]
@bertfrees Can you attach a screenshot? What I'm seeing is that the form sections ("required", "optional") have a max width and the contents within are adapted accordingly.  

There is a possibility to make the max width wider though, maybe that would fix your issue?

**Comment by bertfrees** [comment]
<img width="1056" alt="Screenshot 2023-01-17 at 13 39 03" src="https://user-images.githubusercontent.com/1167989/212901957-71a8c20e-89a3-4bb2-a78d-1b58c18ca7cf.png">

<img width="1919" alt="Screenshot 2023-01-17 at 13 39 19" src="https://user-images.githubusercontent.com/1167989/212902012-e88336c5-1461-4633-8f38-ea0d850a6c14.png">

**Comment by bertfrees** [comment]
I think a wider max width makes sense.
